#%RAML 1.0 Library
uses:
  odata: libraries/odataLibrary.raml

types:
  valuation:
    (odata.remote): Valuation
    properties:
      ValuationRollNumber:
          type: number
          (odata.key): true
          (odata.nullable): false
          format: int32
          required: false
      Assessment:
          type: number
          (odata.key): true
          (odata.nullable): false
          format: int32
      Alphaid:
          type: string
          (odata.key): false
          (odata.nullable): true
      LandDistrict:
          type: string
          (odata.key): false
          (odata.nullable): true
      StreetNumber:
          type: string
          (odata.key): false
          (odata.nullable): true
      FullStreetNumber:
          type: string
          (odata.key): false
          (odata.nullable): true
      RoadNameFull:
          type: string
          (odata.key): false
          (odata.nullable): true
      CertOfTitle:
          type: string
          (odata.key): false
          (odata.nullable): true
      Latitude:
          type: string
          (odata.key): false
          (odata.nullable): true
      Longitude:
          type: string
          (odata.key): false
          (odata.nullable): true
      LegalDescription:
          type: string
          (odata.key): false
          (odata.nullable): true
      InterestArea:
          type: string
          (odata.key): false
          (odata.nullable): true
      CategoryCode:
          type: string
          (odata.key): false
          (odata.nullable): true
      OwnershipTypeCharCode:
          type: string
          (odata.key): false
          (odata.nullable): true
      MultipleCt:
          type: string
          (odata.key): false
          (odata.nullable): true
      ShelterBeltValue:
          type: string
          (odata.key): false
          (odata.nullable): true
      NatureOfImprovement:
          type: string
          (odata.key): false
          (odata.nullable): true
      PlanningZoneCharCode:
          type: string
          (odata.key): false
          (odata.nullable): true
      LandUseCharCode:
          type: string
          (odata.key): false
          (odata.nullable): true
      Units:
          type: string
          (odata.key): false
          (odata.nullable): true
      ParkingAvailable:
          type: string
          (odata.key): false
          (odata.nullable): true
      BuildingAge:
          type: string
          (odata.key): false
          (odata.nullable): true
      Condition:
          type: string
          (odata.key): false
          (odata.nullable): true
      Construction:
          type: string
          (odata.key): false
          (odata.nullable): true
      SiteCover:
          type: string
          (odata.key): false
          (odata.nullable): true
      FloorArea:
          type: string
          (odata.key): false
          (odata.nullable): true
      SlopeOfLandCharCode:
          type: string
          (odata.key): false
          (odata.nullable): true
      ViewTypeCharCode:
          type: string
          (odata.key): false
          (odata.nullable): true
      ViewScopeCharCode:
          type: string
          (odata.key): false
          (odata.nullable): true
      TotalLinedFloorArea:
          type: string
          (odata.key): false
          (odata.nullable): true
      DeckExist:
          type: string
          (odata.key): false
          (odata.nullable): true
      LaundryWorkshopExists:
          type: string
          (odata.key): false
          (odata.nullable): true
      LargeImprovements:
          type: string
          (odata.key): false
          (odata.nullable): true
      CarparksUnderMainRoof:
          type: string
          (odata.key): false
          (odata.nullable): true
      CarparksUnderFreestandingRoof:
          type: string
          (odata.key): false
          (odata.nullable): true
      RevisionDate:
          type: string
          (odata.key): false
          (odata.nullable): true
      CapitalValue:
          type: string
          (odata.key): false
          (odata.nullable): true
      ImprovementValue:
          type: string
          (odata.key): false
          (odata.nullable): true
      LandValue:
          type: string
          (odata.key): false
          (odata.nullable): true
      SaleGroupTypeCode:
          type: string
          (odata.key): false
          (odata.nullable): true
      SaleId:
          type: string
          (odata.key): false
          (odata.nullable): true
      DatePriceAgreed:
          type: string
          (odata.key): false
          (odata.nullable): true
      DateAdvised:
          type: string
          (odata.key): false
          (odata.nullable): true
      SaleAmendment:
          type: string
          (odata.key): false
          (odata.nullable): true
      SaleType:
          type: string
          (odata.key): false
          (odata.nullable): true
      SaleTenure:
          type: string
          (odata.key): false
          (odata.nullable): true
      PriceValueRelationship:
          type: string
          (odata.key): false
          (odata.nullable): true
      BuyerSellerRelationship:
          type: string
          (odata.key): false
          (odata.nullable): true
      GrossSalePrice:
          type: string
          (odata.key): false
          (odata.nullable): true
      NetSalePrice:
          type: string
          (odata.key): false
          (odata.nullable): true
      Chattels:
          type: string
          (odata.key): false
          (odata.nullable): true
      OtherSalePrice:
          type: string
          (odata.key): false
          (odata.nullable): true
      GSTIncluded:
          type: string
          (odata.key): false
          (odata.nullable): true
      PercentageShareOfOwnership:
          type: string
          (odata.key): false
          (odata.nullable): true
